#!/bin/bash
set -euo pipefail

# ── Args ────────────────────────────────────────────────────────────────────
ENV_NAME="${1:-}"
TTL="${2:-1800}"   # default 30 min

if [[ -z "$ENV_NAME" ]]; then
  echo "Usage: $0 <name> [ttl_seconds]"
  exit 1
fi

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENVS_DIR="$PROJECT_ROOT/envs"
LOGS_DIR="$PROJECT_ROOT/logs"
NGINX_CONF_DIR="$PROJECT_ROOT/nginx/conf.d"

# ── Generate unique env ID ───────────────────────────────────────────────────
ENV_ID="env-$(echo $ENV_NAME | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/-*$//')-$(date +%s | tail -c 6)"
NETWORK_NAME="net-$ENV_ID"
CONTAINER_NAME="app-$ENV_ID"
CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "==> Creating environment: $ENV_ID"

# ── Create log directory ─────────────────────────────────────────────────────
mkdir -p "$LOGS_DIR/$ENV_ID"

# ── Create dedicated Docker network ─────────────────────────────────────────
echo "==> Creating Docker network: $NETWORK_NAME"
docker network create "$NETWORK_NAME"

# Connect Nginx container to this network so it can reach the app
docker network connect "$NETWORK_NAME" sandbox-nginx

# ── Start app container ──────────────────────────────────────────────────────
echo "==> Starting app container: $CONTAINER_NAME"
docker run -d \
  --name "$CONTAINER_NAME" \
  --network "$NETWORK_NAME" \
  --label "sandbox.env=$ENV_ID" \
  -e "ENV_ID=$ENV_ID" \
  demo-app:latest

# ── Write Nginx config ───────────────────────────────────────────────────────
echo "==> Writing Nginx config"
NGINX_CONF="$NGINX_CONF_DIR/$ENV_ID.conf"

cat > "$NGINX_CONF" << NGINX
# AUTO-GENERATED by create_env.sh — do not edit manually
# ENV_ID: $ENV_ID

upstream $ENV_ID {
    server $CONTAINER_NAME:5000;
}

server {
    listen 80;
    server_name $ENV_ID.localhost;

    location / {
        proxy_pass http://$ENV_ID;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
NGINX

# ── Reload Nginx ─────────────────────────────────────────────────────────────
echo "==> Reloading Nginx"
docker exec sandbox-nginx nginx -s reload

# ── Start log shipping (Approach A) ─────────────────────────────────────────
echo "==> Starting log shipping"
mkdir -p "$LOGS_DIR/$ENV_ID"
docker logs -f "$CONTAINER_NAME" >> "$LOGS_DIR/$ENV_ID/app.log" 2>&1 &
LOG_PID=$!
echo "$LOG_PID" > "$LOGS_DIR/$ENV_ID/log-shipper.pid"

# ── Write state file atomically ──────────────────────────────────────────────
echo "==> Writing state file"
TEMP_FILE=$(mktemp "$ENVS_DIR/.tmp.XXXXXX")
cat > "$TEMP_FILE" << JSON
{
  "id": "$ENV_ID",
  "name": "$ENV_NAME",
  "container": "$CONTAINER_NAME",
  "network": "$NETWORK_NAME",
  "created_at": "$CREATED_AT",
  "ttl": $TTL,
  "status": "running"
}
JSON
mv "$TEMP_FILE" "$ENVS_DIR/$ENV_ID.json"

# ── Print summary ────────────────────────────────────────────────────────────
echo ""
echo "✅ Environment ready!"
echo "   ID:     $ENV_ID"
echo "   Name:   $ENV_NAME"
echo "   TTL:    ${TTL}s"
echo "   URL:    http://$(curl -s http://checkip.amazonaws.com):80"
echo "   Host header required: $ENV_ID.localhost"
echo ""
echo "   Test with:"
echo "   curl -H 'Host: $ENV_ID.localhost' http://localhost:80/"
echo "   curl -H 'Host: $ENV_ID.localhost' http://localhost:80/health"
