events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/*.conf;

    # Default server — catches requests that don't match any env
    server {
        listen 80 default_server;
        return 404 "No environment found\n";
    }
}
